#!/usr/bin/env bash

###################### COPYRIGHT/COPYLEFT ######################

# (C) 2020..2022 Michael Soegtrop

# Released to the public under the
# Creative Commons CC0 1.0 Universal License
# See https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt

###################### CONTROL VARIABLES #####################

# The two lines below are used by the package selection script
COQ_PLATFORM_VERSION_TITLE="Coq 8.16.0 (released Sep 2022) with a package pick for the 2022 Math Comp school."
COQ_PLATFORM_VERSION_SORTORDER=9000

# The package list name is the final part of the opam switch name.
# It is usually either empty ot starts with ~.
# It might also be used for installer package names, but with ~ replaced by _
# It is also used for version specific file selections in the smoke test kit.
COQ_PLATFORM_PACKAGE_PICK_POSTFIX='~math-comp-school-2022'

# The corresponding Coq development branch and tag
COQ_PLATFORM_COQ_BRANCH='v8.16'
COQ_PLATFORM_COQ_TAG='8.16.0'

# This controls if opam repositories for development packages are selected
COQ_PLATFORM_USE_DEV_REPOSITORY='N'

# This extended descriptions is used for readme files
COQ_PLATFORM_VERSION_DESCRIPTION='This version of Coq Platform 2022.09.0 includes Coq 8.16.0 from Sep 2022. '
COQ_PLATFORM_VERSION_DESCRIPTION+='This is beta release with complete package pick and intended for package maintainers and early adopters. '

# The OCaml version to use for this pick (just the version number - options are elaborated in a platform dependent way)
COQ_PLATFORM_OCAML_VERSION='4.13.1'

###################### PACKAGE SELECTION #####################

PACKAGES=""

# - Comment out packages you do not want.
# - Packages which take a long time to build should be given last.
#   There is some evidence that they are built early then.
# - Versions ending with ~flex are identical to the opam package without the
#   ~flex extension, except that version restrictions have been relaxed.
# - The picking tracker issue is https://github.com/coq/platform/issues/193

########## BASE PACKAGES ##########

# Coq needs a patched ocamlfind to be relocatable by installers
PACKAGES="${PACKAGES} PIN.ocamlfind.1.9.5~relocatable"
# The Coq compiler coqc and the Coq standard library
PACKAGES="${PACKAGES} PIN.coq.8.16.0"
# Since dune does support Coq, it is explicitly selected
PACKAGES="${PACKAGES} dune.3.4.1"
PACKAGES="${PACKAGES} dune-configurator.3.4.1"

########## IDE PACKAGES ##########

# GTK based IDE for Coq - alternatives are VSCoq and Proofgeneral for Emacs
if  [[ "${COQ_PLATFORM_EXTENT}"  =~ ^[iIfFxX] ]]
then
PACKAGES="${PACKAGES} coqide.8.16.0"
fi

########## "FULL" COQ PLATFORM PACKAGES ##########

if  [[ "${COQ_PLATFORM_EXTENT}"  =~ ^[fFxX] ]]
then

  PACKAGES="${PACKAGES} elpi.1.16.5 coq-elpi.1.15.6"
  PACKAGES="${PACKAGES} coq-hierarchy-builder.1.4.0"
  PACKAGES="${PACKAGES} coq-mathcomp-ssreflect.2.0.0+alpha1"
  PACKAGES="${PACKAGES} coq-mathcomp-fingroup.2.0.0+alpha1"
  PACKAGES="${PACKAGES} coq-mathcomp-algebra.2.0.0+alpha1"
  PACKAGES="${PACKAGES} coq-mathcomp-solvable.2.0.0+alpha1"
  PACKAGES="${PACKAGES} coq-mathcomp-field.2.0.0+alpha1"
  PACKAGES="${PACKAGES} coq-mathcomp-character.2.0.0+alpha1"

#  PACKAGES="${PACKAGES} coq-mathcomp-algebra-tactics.1.0.0"

fi