#!/bin/bash

# This shell scripts uses the path of the script itself to
# set the COQBIN, COQLIB and PATH variables before invoking
# the real program

export COQBIN="$(cd $(dirname $0); pwd)"
export COQLIB="$(cd $(dirname $0)/../lib/coq/; pwd)"
SELF="$(basename $1)"

shift # drop $1

# this path also contains coq extra utilities like gappa
export PATH="$COQBIN:$PATH"

# This is required for OCaml findlib
# Example path: /snap/coq-prover/x1/coq-platform/2022-09-0/lib/findlib.conf
# Snap environmet variables: See https://snapcraft.io/docs/environment-variables
export OCAMLFIND_CONF="${SNAP}/coq-platform/${SNAP_VERSION}/lib/findlib.conf"

if [ "$SELF" == "bash" -o "$SELF" == "sh" ]; then # for debugging the snap
  exec $SELF "$@"
elif [ "$SELF" == "coq_makefile" ]; then
  exec $COQBIN/$SELF COQBIN = "$COQBIN/" "$@"
else
  exec $COQBIN/$SELF "$@"
fi