#!/bin/bash

# This shell scripts uses the path of the scipt itself to
# set the COQBIN directory

export COQBIN="$(cd $(dirname $0); pwd)"
export COQLIB="$(cd $(dirname $0)/../lib/coq/; pwd)"

SELF="$(basename $1)"

shift # drop $1

if [ "$SELF" == "coq_makefile" ]; then
  exec $COQBIN/$SELF COQBIN = "$COQBIN/" "$@"
else
  exec $COQBIN/$SELF "$@"
fi