#!/bin/bash

# This shell scripts uses the path of the scipt itself to
# set the COQBIN directory

export COQBIN="$(cd $(dirname $0); pwd)"
export COQLIB="$(cd $(dirname $0)/../lib/coq/; pwd)"

THIS="$(basename $0)"
SELF="${THIS##coq_wrapper_}"

if [ "$SELF" == "coq_makefile" ]; then
  exec $(dirname $0)/$SELF COQBIN = "$COQBIN/" "$@"
else
  exec $(dirname $0)/$SELF "$@"
fi